### ISSUE TITLE
False detections on anti-virus software.

### ISSUE THREAD

**Issue by Luca06Luwa** [NotsoFrostyy/Image-Converter#1]
Looking on virus total, it reported that two anti-virus software's detected it as malware. Only posting issue purely for bug tracking purposes.

**Comment by NotsoFrostyy** [comment]
> Looking on virus total, it reported that two anti-virus software's detected it as malware. Only posting issue purely for bug tracking purposes.

I'm looking into a fix but looks like any exes made by pyinstaller are false detected

**Comment by NotsoFrostyy** [comment]
exes compiled with pyinstaller get false detected there is no fix atm, all my code is open source for anyone to look at.

for more info look at this: https://github.com/pyinstaller/pyinstaller/issues/6754#issuecomment-1100821249
